version: '3.4'

services:
  rasa:
    image: rasa/rasa:3.0.8-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    environment:
      MPLCONFIGDIR: "/tmp/"
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"


  action_server:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"
