version: “3.4”
services:
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - "5005:5005"
    
  action_server:
    image: rasa/rasa-sdk:3.0.0
    volumes:
    -  ./actions:/app/actions
    ports:
      - "5055:5055"
      
  duckling:
    image: rasa/duckling:latest
    ports:
    - "8000:8000"
