version: '3.7'
services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
    - 8000:8000
    networks:
    - all

  rasa:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    command: bash -c "rasa train && rasa run --model models/ --enable-api --cors \"*\" -p 8080 --debug"
    ports:
      - '5005:8080' #external:internal
    networks:
      - all

  rasa-actions-server:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
      - '5055:5055'
    networks:
      - all


networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
