version: '3.4'

services:
  rasa:
    image: rasa-bot:latest
    networks: ['rasa-network']
    working_dir: /app
    ports:
    - "5005:5005"
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
